    FROM aeternity/aeternity:v3.1.0
    COPY ./aeternity.yaml /home/aeternity/node/aeternity.yaml
    user root
    VOLUME /data/node-db
    # RUN chown -R aeternity: /home/aeternity/
    # user aeternity
